name: stealth_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async:
  badges:
  characters:
  crypton:
  cupertino_icons:
  emoji_picker:
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
      ref: 42ba773
  file_picker:
  filesize:
  firebase_core:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_colorpicker:
  flutter_ffmpeg:
  flutter_image_compress:
  flutter_linkify: 4.0.2
  font_awesome_flutter:
  get:
  gradient_widgets:
  html:
  http:
  image_picker: 0.7.2
  ini:
  intl:
  json_serializable:
  logging:
  moor: 4.1.0
  open_file:
  package_info:
  path:
  path_provider:
  phoenix_socket:
  qr_code_scanner:
  qr_flutter:
  share:
  shared_preferences:
  steel_crypt:
  sqlite3_flutter_libs:
  synchronized:
  tinycolor:
  tuple:
  uni_links:
  url_launcher:
  uuid:
  video_compress:

dev_dependencies:
  build_runner:
  flutter_launcher_icons: 0.9.0
  flutter_test:
    sdk: flutter
  freezed:
  moor_generator:

dependency_overrides:
  args: 2.0.0
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

flutter:
  uses-material-design: true
  assets:
    - assets/app.properties
    - assets/images/notifications_prompt.jpg
    - assets/images/enable_notifications_steps.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
