name: stealth_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: 
  badges: 1.1.6
  characters:
  crypton: 1.1.3
  cupertino_icons: 1.0.0
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption 
  flutter:
    sdk: flutter
  font_awesome_flutter: 8.11.0
  get: 3.24.0
  gradient_widgets: 0.5.2
  html: 0.14.0 
  http: 0.12.1
  ini:
  intl: 0.16.1
  json_serializable: 
  logging:
  moor: 3.4.0
  package_info: 
  path:
  path_provider:
  phoenix_socket: 0.4.11
  share: '>=0.6.5+4 <2.0.0'
  shared_preferences: 
  steel_crypt: 
    git:
      url: https://github.com/AKushWarrior/steel_crypt.git
      ref: 662008c
  sqlite3_flutter_libs: 0.3.0
  tinycolor: 1.0.3
  tuple:
  uni_links: 0.4.0
  uuid:
  web_socket_channel:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: 0.12.7 
  moor_generator: 

flutter:
  uses-material-design: true
  assets:
    - app.properties